### ISSUE TITLE
Can be used on images outside dataset?

### ISSUE THREAD

**Issue by kharanshu2** [jrzech/reproduce-chexnet#13]
First of all great work.
Secondly:
How do i use it on images that are outside the dataset, i wanna use the pretrained model checkpoint and put 1 image at a time to print it's preds. From my testing if i change the folder and put a random image innit it tells me some other image is not found? is the preds just printing from whatever is stored?

**Comment by jrzech** [comment]
Thanks. If you want to evaluate individual images of your own, you'll need to make a CSV in the format of nih_labels.csv but describing your own data, and change the code to use your CSV rather than nih_labels.csv. The code relies on this CSV to tell it what files exist and what their labels are.

**Comment by kharanshu2** [comment]
great, but why are there class columns with 1 and 0, does that mean I need to know what disease patient has before using the image?

**Comment by jrzech** [comment]
Those columns are used for training and evaluation. If you just want to
make predictions, you could just make all those columns 0 in your csv. It
won’t change predictions. But the code will expect to see those column
headers in your csv.
