### ISSUE TITLE
some labels inconsistent with NIHCC/Data_Entry_2017.csv

### ISSUE THREAD

**Issue by husisy** [jrzech/reproduce-chexnet#2]
Hi,

Thanks for your great work.

I am confused why there are some inconsistency between labels from [NIHCC Data_Entry_2017.csv](https://nihcc.app.box.com/v/ChestXray-NIHCC/folder/36938765345) and from your repo (nih_labels.csv). For example:

00000150_002.png
label in Data_Entry_2017.csv: Atelectasis|Infiltration|Pneumonia
label in nih_labels.csv: Atelectasis|Infiltration

00000193_019.png
label in Data_Entry_2017: Pneumonia
label in nih_labels.csv: No Finding(normal)

('00000830_000.png', '00000902_001.png',... etc.)

**Comment by jrzech** [comment]
Hi Chao, thanks for your message. NIH has apparently released several
versions of the label file, and the one I have been working with was the
version available as of 11/10/2017.

**Comment by husisy** [comment]
got it, thanks for you reply.
