### ISSUE TITLE
Horizontal Flipping in Training?

### ISSUE THREAD

**Issue by kmader** [jrzech/reproduce-chexnet#3]
I briefly looked through the paper again and didn't see any explicit steps on their augmentation workflow, but I would be curious on how performance changes with the horizontal flipping removed.
https://github.com/jrzech/reproduce-chexnet/blob/79ffc2b66da12836902ea7b3f216dd96275d4148/model.py#L223

In particular with cardiomegaly (big heart), the heart is always expected to be on the left-side and so flipping could cause a lower score there.

**Comment by jrzech** [comment]
I haven't explored that myself, but would be interesting to check out.
