### ISSUE TITLE
What are the values in label_baseline_probs, how to come up with that

### ISSUE THREAD

**Issue by subramanya2107** [jrzech/reproduce-chexnet#4]
in calc_cam function in visualize_prediction.py
`label_baseline_probs={
        'Atelectasis':0.103,
        'Cardiomegaly':0.025,
        'Effusion':0.119,
        'Infiltration':0.177,
        'Mass':0.051,
        'Nodule':0.056,
        'Pneumonia':0.012,
        'Pneumothorax':0.047,
        'Consolidation':0.042,
        'Edema':0.021,
        'Emphysema':0.022,
        'Fibrosis':0.015,
        'Pleural_Thickening':0.03,
        'Hernia':0.002
    }
    `

**Comment by jrzech** [comment]
These are baseline probabilities of each finding in the overall NIH
dataset; you can calculate them using the NIH label csv.
