### ISSUE TITLE
Official dataset split

### ISSUE THREAD

**Issue by guanqj932** [jrzech/reproduce-chexnet#5]
Hi, 
I am curious about you dataset split. Is it same as the split provided by NIH? Thanks

**Comment by jrzech** [comment]
There is no official dataset split provided by NIH. The Stanford team didn't disclose the split they used, so it is not possible to replicate theirs exactly. The overall percentage of the dataset in each fold is the same (70% train / 10% tune / 20% test), but the individual cases are randomly selected and are not the same as those used by the Stanford team.
