### ISSUE TITLE
“no improvement in 3 epochs, break” happened at epoch 20

### ISSUE THREAD

**Issue by JaneTakanashi** [jrzech/reproduce-chexnet#6]
I used 8 gpus and default settings, but it was broke at epoch 20 with acu around 0.7, do you have any ideas?

**Comment by jrzech** [comment]
Would not be surprising for the model to converge after 20 epochs; in my experience it typically converges even faster. AUC for some diagnoses (e.g., infiltration) typically plateaus around 0.7.
