### ISSUE TITLE
Errors for '_DenseLayer' object has no attribute 'memory_efficient'

### ISSUE THREAD

**Issue by ywang06** [jrzech/reproduce-chexnet#9]
When running the code on google colab, this error always happen when executing:
raw_cam = calc_cam(inputs, LABEL, model)
I have followed the steps of the following to setup the environment, but the error is consistent. Thank you so much for any help! 

!wget -c https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh
!chmod +x Anaconda3-5.1.0-Linux-x86_64.sh
!bash ./Anaconda3-5.1.0-Linux-x86_64.sh -b -f -p /usr/local
!conda install -y --prefix /usr/local -c <<<your wish>>>>

import sys
sys.path.append('/usr/local/lib/python3.6/site-packages/‘). — deleted, because there is error

Then, set environment

!cd reproduce-chexnet (already in the directory by mounting)
!conda env create -f environment.yml. (only needed the first time, for second time, only need !source postBuild, and !source activate reproduce-chexne )
!source postBuild
!source activate reproduce-chexnet

**Comment by jrzech** [comment]
I just re-cloned it, recreated the conda environment on a linux machine, and ran the code without issue. I think you're likely running into a pytorch version issue. The code requires pytorch 0.2.0, which postBuild installs. I suspect that your google colab setup is causing the conda environment creation to fail in some way. I would review the output from the conda env create and source postBuild commands.

**Comment by ywang06** [comment]
Hi John,

Thank you so much for your help! I will try it again in a clean virtual
machine enviornment and reinstall the process. May I ask for testing
only, without training, do I need GPU support?

Best Regards,
Ying

**Comment by ywang06** [comment]
Hi John,

Thank you so much for your reply. I will try it again in a clean virtual machine environment and reinstall the process. May I ask for testing only, without training, do I need GPU support? 

Best Regards,
Ying

**Comment by jrzech** [comment]
For testing only, you shouldn't need a GPU.
